includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: ../dataset/cifar100
image_size: 32
save_path: ./
# data
init_cls_num: 5
inc_cls_num: 5
task_num: 20

###########

epoch: 200
device_ids: 0
n_gpu: 1
val_per_epoch: 5

batch_size: 64

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

# 暂时启用 backbone 选项
# backbone:
#   name: resnet32_V2
#   kwargs:
#     num_classes: 100
#     args: 
#       dataset: cifar100


# 暂时启用 buffer 选项
# buffer:
#   name: LinearBuffer
#   kwargs:
#     buffer_size: 2000
#     batch_size: 128
#     strategy: herding     # random, equal_random, reservoir, herding


classifier:
  name: ACL
  kwargs: 
    
